package types

import (
	"encoding/json"
	"fmt"
	"net/http"
)

type Url struct {
	Key           string `json:"key"`
	Url           string `json:"url"`
	Code          int    `json:"code"`
	Autogenerated bool   `json:"autogenerated"`
}

func (url *Url) ToHttpResponse(w http.ResponseWriter) {
	js, err := json.Marshal(url)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}
	w.Header().Set("Content-Type", "application/json")
	_, _ = w.Write(js)
}

func (url Url) ToString() string {
	autogen := 0
	if url.Autogenerated {
		autogen = 1
	}
	return fmt.Sprintf("%d %d %s", url.Code, autogen, url.Url)
}

func FromString(str string) (Url, error) {
	var url Url
	var autogen int
	var err error
	_, err = fmt.Sscanf(str, "%d %d %s", &url.Code, &autogen, &url.Url)
	if err != nil {
		return url, err
	}
	url.Autogenerated = autogen == 1
	return url, nil
}
