// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import (
	"bytes"
	"encoding/json"
	"strings"
	"text/template"

	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Nikolay Vasilev",
            "email": "nikhovas@yandex.ru"
        },
        "license": {
            "name": "MIT",
            "url": "https://github.com/nikhovas/goshort/blob/master/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/urls/": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Url"
                ],
                "summary": "Create url by sent data",
                "operationId": "postUrl",
                "parameters": [
                    {
                        "description": "This is body string param",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Url"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Successfully created",
                        "schema": {
                            "$ref": "#/definitions/types.Url"
                        }
                    },
                    "400": {
                        "description": "Bad input data"
                    }
                }
            }
        },
        "/urls/{key}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Url"
                ],
                "summary": "Get url by key",
                "operationId": "getUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Url key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Url"
                        }
                    },
                    "400": {
                        "description": "Bad input data"
                    },
                    "404": {
                        "description": "No such url"
                    }
                }
            },
            "delete": {
                "tags": [
                    "Url"
                ],
                "summary": "Delete url by key",
                "operationId": "deleteUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Url key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Successfully deleted"
                    },
                    "400": {
                        "description": "Bad input data"
                    },
                    "404": {
                        "description": "No such url"
                    }
                }
            },
            "patch": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Url"
                ],
                "summary": "Edit url by sent data",
                "operationId": "patchUrl",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Url key",
                        "name": "key",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "This is body string param",
                        "name": "url",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/types.Url"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/types.Url"
                        }
                    },
                    "400": {
                        "description": "Bad input data"
                    },
                    "404": {
                        "description": "No such url"
                    }
                }
            }
        }
    },
    "definitions": {
        "types.Url": {
            "type": "object",
            "properties": {
                "autogenerated": {
                    "type": "boolean",
                    "example": false
                },
                "code": {
                    "type": "integer",
                    "example": 301
                },
                "key": {
                    "type": "string",
                    "example": "example"
                },
                "url": {
                    "type": "string",
                    "example": "example.com"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "",
	BasePath:    "/api/",
	Schemes:     []string{},
	Title:       "Goshort Swagger API",
	Description: "Swagger API for Golang Project Goshort.",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
		"escape": func(v interface{}) string {
			// escape tabs
			str := strings.Replace(v.(string), "\t", "\\t", -1)
			// replace " with \", and if that results in \\", replace that with \\\"
			str = strings.Replace(str, "\"", "\\\"", -1)
			return strings.Replace(str, "\\\\\"", "\\\\\\\"", -1)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
