name: dockerize
on:
  workflow_run:
    workflows: ["test", "lint"]
    branches: [master]
    types:
      - completed

jobs:
  dockerize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push standalone
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./standalone.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: nikhovas/goshort:alpine
      - name: Build and push with redis
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./redis.Dockerfile
          platforms: linux/amd64,linux/arm64,linux/386
          push: true
          tags: nikhovas/goshort:redis